### PR TITLE
Added forum stylesheet theme selection

### PR DESCRIPTION
**Pull request by Hisol**
Thought it would be useful to be able to define custom styles for the forum.

### CODE REVIEW

**Comment by Asgaros** [comment]
Hey @Hisol 

I think one thing which should be changed is the location for custom themes. They should be saved somewhere outside of the plugin-folder. Maybe in _/wp-content/themes-asgaros-forum/_. The reason for this is that a new version of the plugin will override all files in the plugin-directory so custom changes will be more safe outside of this directory.

**Comment by Hisol** [comment]
I was thinking that if someone creates their own theme (not edit one of the existing example themes) then these files wouldn't be removed.  I guess an update removes any files not in the current version to save having lots of orphaned files left lying around.  I'll get on it now :)

**Comment by Hisol** [comment]
Have moved theme's into wp-content/asgaros-themes and rebased my commits against current head.

**Comment by Asgaros** [comment]
Some more things:

1. What happens when there is a theme called "default" in the themes-directory? Maybe this one should be ignored so we can ensure that it is always possible to select the original default-theme.
2. Maybe the "default" theme can be copied to the themes-directory as an example. The name should be changed after it from "default" to "example" (because of 1.). The example-themes in your PR are almost the same so there would be less redundant code.
3. I am not sure if the color-picker makes sense when you use a theme other than the default theme because everyone who is able to modify a theme should be able to set the colors without the color-picker as well. Any suggestions/thoughts/ideas about it?

**Comment by Hisol** [comment]
1) Good point, I'll fix that
2) That makes sense, I added the extra themes to allow end user to see a difference.  It is kinda pointless.  I will either have a stab at adjusting the theme more, to give it more use than an example.  Otherwise I'll just copy in the existing theme and leave it as an example base
3) I agree, I left it in as it is used by the example themes.  I'll strip it out of the static themes, if something crops up later can always tweak and add something in :)

**Comment by Hisol** [comment]
1 & 3 done.  The colour picker on the options page might be a bit ugly, I have just added some text to indicate it's only for the default forum.  Just going to create an example theme now.

**Comment by Hisol** [comment]
I have removed one example theme and changed the colours for shades of grey and white creating a Dark theme for use on sites that have a dark background colour.  It does duplicate the basic skin theme, but I think also adds usability for anyone who has a dark background site that wishes to use the forum.  (I freely admit I am no web designer and have very limited artistic talent :D )

**Comment by Asgaros** [comment]
Great so far! But a couple of more improvements:

1. The dark theme needs some more modifications. I think at least all text and icons should be viewable even if you use a non-dark WordPress-template. It would be a little bit weird if parts of the forums are not viewable in this case. darktheme
2. There has to be some check that in each theme-directory is a style.css file. We should ingore the directory if it is not there. Other files should be optional so for example we dont need to include a mobile.css-file when there is no mobile.css-file in the theme-directory.

**Comment by Hisol** [comment]
1) I'm not much of a web designer, but I'll have a crack at it :)  worth noting that this exact problem is part of the reason I thought of this feature.  I have a site with a black background and the current skin is VERY difficult to read on it.

2) Good point, I'll get that sorted.

**Comment by Asgaros** [comment]
1) Yes, I understand this. But I think both themes should be looking ready to use on dark and light WordPress-templates. If this is not the case people may be asking why theme X is looking broken with their WordPress theme.

If you can give me a link to your forum-website I can fix some compatibility problems. :)

**Comment by Hisol** [comment]
Have made those changes, how is that looking now?

**Comment by Hisol** [comment]
The website isn't online at the moment.  What do you think of the tweaked theme?  Just noticed there are now some conflicts also, when I get chance I'll get those resolved too.

**Comment by Hisol** [comment]
Have resolved the conflict and squashed commits.

**Comment by Asgaros** [comment]
I will check it the next few hours/days. Dont worry! :)

**Comment by Hisol** [comment]
:) Happy to help out, no worries :)

**Comment by Asgaros** [comment]
Can you please check the selection of the themes? When I select the "Dark theme" and press save, it will be selected, but when I refresh the option page, the "Default" theme is selected again. Inside the frontend the default theme will be loaded as well.

**Comment by Hisol** [comment]
Will look into it, I had that bug myself but thought I had squashed it.. pesky thing.. Will iron that out

**Comment by Hisol** [comment]
I cannot get this bug to occur for me!  What version of wordpress are you running? web-browser?  Is it a fresh install of the forum or an existing one?

**Comment by Asgaros** [comment]
Mh okay, I will merge and check it out later. I am still not pretty sure about the example-theme workflow in combination with the color picker. Can you please subscribe to this issue so we can continue the conversation there after the merge: https://github.com/Asgaros/asgaros-forum/issues/70

**Comment by Hisol** [comment]
Github claims I am already subscribed to it as you have mentioned me in it :)  Happy to slay any bugs, and improve also.  I'll think on the colour picker, I have an idea but it's still a bit in it's infancy so want to think on it further :)

**Pull request merged**
