### PR TITLE
Frontend profile editing

### PR DESCRIPTION
**Pull request by glorious1**
Thomas, I know this is a lot of change to consider, and frankly I am no php expert.  I coded it like a monkey, copying and imitating your code and some others.  Also, github is even more confusing to me with all the pushing and pulling, merging and committing, upstream and master.  

All that said, it works for me.  I can't guarantee it will work in different environments with different settings.  I tested as much as I know how.

I'll attach a text document that summarizes the file changes and includes some notes.
Jim
[asgaros_editprofile_edits.txt](https://github.com/Asgaros/asgaros-forum/files/7981284/asgaros_editprofile_edits.txt)

### CODE REVIEW

**Comment by Asgaros** [comment]
Thanks @glorious1 

Still thinking on how to merge that in the mid-term. As you said its a huge change, but I will definitely include it sooner or later. :)

**Comment by glorious1** [comment]
Sorry, that's me not understanding github.  I do have this fully functioning with 2.6.0.

**Comment by Asgaros** [comment]
@glorious1 Can you create another PR or Issue and attached the code to there? It seems you deleted by accident your repository.

**Comment by glorious1** [comment]
I tried to update my repository but I hopelessly messed it up and didn't know how to fix it, so I deleted it, not realizing it would affect the pull request.  Then I recreated it.  I cloned your repo to my local computer, branched it to make the edit-profile changes, committed, and pushed it to my new github repository.  Except now it is in branch 'master', and I don't know how to make it 'main'.  Github is smarter than me.

Anway, yes, I'll see what I can do about a new PR.

**Pull request closed without merging**
